site_name: <SITE NAME>
# repo_url: <URL GOES HERE>
# repo_name: <USERNAME/REPOSITORY_NAME>
edit_uri: ''
plugins:
  - mkdocs-versioning:
      version: 1.0.0
nav:
  - Home : 'index.md'
  - Circle: 'circle.md'
  - Version: '../'
